"""empty message

Revision ID: e3ee81bcbcbe
Revises: ec26a14dc315
Create Date: 2018-11-24 16:55:19.542848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ee81bcbcbe'
down_revision = 'ec26a14dc315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PasteFile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=5000), nullable=False),
    sa.Column('filehash', sa.String(length=128), nullable=False),
    sa.Column('filemd5', sa.String(length=128), nullable=False),
    sa.Column('uploadtime', sa.DateTime(), nullable=False),
    sa.Column('mimetype', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filehash'),
    sa.UniqueConstraint('filemd5')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PasteFile')
    # ### end Alembic commands ###
